
taco:
  orders:
    pageSize: 10
spring:
  thymeleaf:
    cache: false

logging:
  path: /var/logs/
  file: TacoCloud.log
  level:
    root: warn
    tacos: debug
    org.springframework.security: debug