
taco:
  orders:
    pageSize: 10
spring:
  thymeleaf:
    cache: false
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
logging:
  path: /var/logs/
  file: TacoCloud.log
  level:
    root: warn
    tacos: debug
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
#    org.springframework.security: debug
    org.springframework.web: debug